name: xingxbgzc

on:
  workflow_dispatch:
  schedule:
    - cron: '16 1/6 * * *'
jobs:  # 16338
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xingxbgzc
        env:
          qxzc1987: ${{ secrets.qxzc1987 }}
        run: |
          echo $qxzc1987 | jq -r .f1 | /bin/bash
          echo $sqcp68114 | jq -r .asd74207 | /bin/bash
          echo $kl78356 | jq -r .asgbo7498 | /bin/bash
          echo $xmhn91834 | jq -r .ahi878 | /bin/bash

